config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'paintings#index'

  resources :paintings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  #attr_accessible :image, :name
  mount_uploader :image, ImageUploader

  before_create :default_name

  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
	
	def index
		@paintings = Painting.all
	end
	def show
		@painting = Painting.find(params[:id])
	end

	def new
		@painting = Painting.new
	end
	def edit
		 @painting = Painting.find(params[:id])
	end
	def create
		@painting = Painting.new(painting_params)
       
         if @painting.save
            redirect_to @painting
	      else
	      	render 'new'
         end
    end
     def update
	    @painting = Painting.find(params[:id])
	 
	  if @painting.update(painting_params)
	    redirect_to @painting
	  else
	    render 'edit'
	  end
	end
def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
 
    redirect_to paintings_path
  end
	private
    def painting_params
      params.require(:painting).permit(:image)
    end


 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Image</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paintings/_painting.html.erb
<div class="painting">
  <%= link_to image_tag(painting.image.url(:thumb)), painting if painting.image? %>
  <div class="name"><%= painting.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_painting_path(painting) %> |
    <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/paintings/create.js.erb
<% if @painting.new_record? %>
  alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#paintings").append("<%= j render(@painting) %>");
<% end %>

app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>

<div id="paintings">
  <%= render @paintings %>
</div>
<div class="clear"></div>

<%= form_for Painting.new do |f| %>
  <%= f.label :image, "Upload paintings:" %>
  <%= f.file_field :image, multiple: true, name: "painting[image]" %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>



<script type="text/javascript">
  $( document ).ready(function() {
    $('#new_painting').fileupload({
      dataType: "script",
      add: function(e, data) {
        var file, types;
        types = /(\.|\/)(gif|jpe?g|png)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.context = $(tmpl("template-upload", file));
          $('#new_painting').append(data.context);
          return data.submit();
        } else {
          return alert(file.name + " is not a gif, jpeg, or png image file");
        }
      },
      progress: function(e, data) {
        var progress;
        if (data.context) {
          progress = parseInt(data.loaded / data.total * 100, 10);
          return data.context.find('.bar').css('width', progress + '%');
        }
      }
    });
  });
</script>

app/views/paintings/new.html.erb
<h1> new painting </h1>
<%= form_for Painting.new, :html => {:multipart => true} do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p><%= form.label :image, "upload paintings:" %><br>
    <%= form.file_field :image, multiple: true, name: "painting[image]" %>
    </p>
  <%= form.submit %>
  <% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>


<%= link_to 'Back', paintings_path %>

app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>


<p><%= image_tag @painting.image.url %></p>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>